CREATE TABLE TOPIC(
  TOPIC_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  DESCRIPTION VARCHAR(800)
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  LAST_SEEN DATETIME
);

CREATE TABLE CHAT_REQUEST(
  USER_ID BIGINT NOT NULL,
  TOPIC_ID BIGINT NOT NULL,
  EXPIRES DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID, TOPIC_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
  FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC(TOPIC_ID)
);
